### ISSUE TITLE
Addition of new test cases

### ISSUE THREAD

**Issue by asrjy** [henze-research-group/MODRLC#40]
Hello. I see that there is only one complete test case (spawn ref small office) and another in development (spawn ref medium office). Is there any way we can build our own test cases using BOPTEST or a prototype building model? Or are you planning on adding other test cases soon?

**Comment by ThibaultMarzullo** [comment]
Hello @asrjy ,
We have built and integrated a set of tools that allow you to easily import Spawn of EnergyPlus models into the ACTB, so if you have a Spawn model I can give you some instructions on how to generate the test case resources.
I should also update the user guide to include instructions to these new features, and instructions on how to create a Spawn model.
We are also in the process of creating a companion program for generating Spawn models from original EnergyPlus models, but it is only at prototype stage now and it might be a couple of months before we release this.
I will keep this issue open and keep you and other users updated on the new features. If you want to start a discussion on the items above, we can use this thread.

**Comment by asrjy** [comment]
Hi @ThibaultMarzullo , could you please point me towards some resources from where I can create an SOEP model? 
Also can this be used with a custom weather file? I want to test the model on the NREL prototype buildings (https://www.energycodes.gov/prototype-building-models) but I can't find the SOEP models for these buildings.

**Comment by ThibaultMarzullo** [comment]
Hi @asrjy , apologies for the late reply.
You can have a look at section 4.2 of [this document](https://github.com/henze-research-group/MODRLC/blob/actb-manual/docs/ACTB_Manual.pdf), it explains how to develop a SOEP model using the Modelica Buildings Library. You will need some knowledge of Modelica for that, as the HVAC portion is developed entirely in Modelica. The guide explains how to link the Modelica model to an EnergyPlus model (and weather file).
The rest of the document is somewhat out of date, we are in the process of updating it.
I hope this helps.
Thibault

**Comment by 1kingreenTHU1** [comment]
Hello.  Could I run this testbed on a Linux system not on a Unix system.

**Comment by ThibaultMarzullo** [comment]
Hi @1kingreenTHU1 , yes you can run this on linux and mac natively, and with a few tweaks also on Windows.

**Comment by ThibaultMarzullo** [comment]
Closing this until there is more activity
