### ISSUE TITLE
no matching tensor flow when installing requirements.txt

### ISSUE THREAD

**Issue by P11GH** [henze-research-group/MODRLC#43]
Hi, I use the command "pip3 install -r requirements.txt", but it reported that 
<img width="578" alt="image" src="https://github.com/henze-research-group/MODRLC/assets/50893243/9214b475-02be-49e5-ae32-ff72feab38d5">
Would you help to solve the issue?

**Comment by ThibaultMarzullo** [comment]
Hi @P11GH, have you resolved your issue? Was the problem related to the ACTB or was it specific to your machine? Is there anything we can do to improve the ACTB in this regard?
Thank you

**Comment by P11GH** [comment]
Hi Thibault, it is solved after I updated pip to the latest version. Thanks for asking.
