### ISSUE TITLE
python version and SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by P11GH** [henze-research-group/MODRLC#44]
Hi, I am running the case of MPC-spawnrefsmalloffice-DRevent with the command "python3 main.py", but it reported "SyntaxError: future feature annotations is not defined". I searched the internet, it told me that the feature is supported from python 3.7. But the readme file of ACTB in this MODRLC repo recommends using python 3.6. 
Would you help to look into the issue and help to solve it?

**Comment by mattrobmattrob** [comment]
This should be set up for using Python 3.9 with `pyenv` at this point after the change in https://github.com/henze-research-group/MODRLC/pull/45. Please re-open this issue, if that's not true.
