### ISSUE TITLE
Makefile:31 & Makefile:18 Error 2   

### ISSUE THREAD

**Issue by LindsayRex** [henze-research-group/MODRLC#57]
Hi,

1. I am tring to stand up the default  ACTB  test cass, as per the /modrlc/readme.md  but whenever i run the make run,   make run TESTCASE=spawnrefsmalloffic. I get this error: 

(.venv) rexl1@Dev2:~/Documents/GitHub/MODRLC$ make run TESTCASE=spawnrefsmalloffice
make run-detached
make[1]: Entering directory '/home/rexl1/Documents/GitHub/MODRLC'
(cd boptest-service && docker-compose up -d web worker)
boptest-service_redis_1 is up-to-date
boptest-service_goaws_1 is up-to-date
boptest-service_minio_1 is up-to-date
Starting boptest-service_mc_1 ... done
boptest-service_worker_1 is up-to-date
boptest-service_web_1 is up-to-date
make[1]: Leaving directory '/home/rexl1/Documents/GitHub/MODRLC'
make provision
make[1]: Entering directory '/home/rexl1/Documents/GitHub/MODRLC'
(cd boptest-service/provision && docker-compose run --no-deps provision python3 -m boptest_submit ../boptest/testcases/spawnrefsmalloffice)
WARNING: The BOPTEST_TEST_PRIVILEGED_KEY variable is not set. Defaulting to a blank string.
WARNING: The MINIO_ROOT_USER variable is not set. Defaulting to a blank string.
WARNING: The MINIO_ROOT_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
WARNING: The AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
Creating boptest-service_provision_run ... done
usage: __main__.py [-h] [-a AUTH_TOKEN] [-s] [-d] [-p PATH]
__main__.py: error: unrecognized arguments: ../boptest/testcases/spawnrefsmalloffice
ERROR: 2
make[1]: *** [makefile:31: provision] Error 2
make[1]: Leaving directory '/home/rexl1/Documents/GitHub/MODRLC'
make: *** [makefile:18: run] Error 2

I dont know if this is related to point two or a seperate issue? 

2. Secodnly i noice that the two of the dockers also start and then exit. i dotn know if that is normal. 

I am trying  to run this all locallay  my VM Ubuntu 22 machine. See the two red  screen containers that have exited.. 
 

![Screenshot from 2024-04-03 11-50-14](https://github.com/henze-research-group/MODRLC/assets/122247996/7dbad819-3e87-4020-9eb2-eeb52ba324ef)

3. I get the same result when i run the test cases as well,
 
## Quick-Start to Run Test Cases

1. Make sure the Docker daemon is running. 
2. Build the Docker containers by running ``$ make build``
3. Run the Docker containers by running ``$ make run``

cli output: 

Creating boptest-service_provision_run ... done
usage: __main__.py [-h] [-a AUTH_TOKEN] [-s] [-d] [-p PATH]
__main__.py: error: unrecognized arguments: ../boptest/testcases/
ERROR: 2
make[1]: *** [makefile:31: provision] Error 2
make[1]: Leaving directory '/home/rexl1/Documents/GitHub/MODRLC'
make: *** [makefile:18: run] Error 2

I hope someone can point me in the right diretcion to a fix? 

Thank you kindly,

Lindsay Rex

**Comment by mattrobmattrob** [comment]
I will look tomorrow, this was likely broken as part of my large refactor that was just merged.

**Comment by LindsayRex** [comment]
I fixed it.   
 the master /modrlc/makefile   needed  a -p  
 
 Based on the error message, it appears that the boptest_submit command is not recognizing the argument ../boptest/testcases/ passed to it.

 line 30/31 
 
  provision:
    (cd boptest-service/provision && docker-compose run --no-deps provision python3 -m boptest_submit -p ../boptest/testcases/${TESTCASE})

...these are the best kinda bugs..?  Self fixing!

Cheers,

Lindsay 
![Screenshot from 2024-04-03 13-08-18](https://github.com/henze-research-group/MODRLC/assets/122247996/d85172d6-4e5e-4e64-b1b8-5d497d0de1df)

**Comment by mattrobmattrob** [comment]
Do you mind submitting a PR with the fix?
